#!/usr/bin/env python

import sys

from ros_groundstation.my_module import GroundStationPlugin
from rqt_gui.main import Main

plugin = 'Ground Station'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
