#!/usr/bin/env python

import sys

from ros_groundstation.gs_plugin import GroundStationPlugin
from rqt_gui.main import Main

plugin = 'ros_groundstation'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
